ECHO OFF

REM #SIMPLE TEST with DEFINED LABEL and TIMESTAMP for VIEW NAME
sde_perl viewConfiguration.pl -L CRH1090921_R1C028  -v
echo 
PAUSE

REM #TEST with DEFINED LABEL and VIEW NAME
sde_perl viewConfiguration.pl -L CRH1090921_R1C028 -V TEST_VIEWCONFIGURATION -v
echo 
PAUSE    

REM #TEST with DEFINED LABEL and VIEW NAME  THAT ALREADY EXIST
sde_perl viewConfiguration.pl -L CRH1090921_R1C028 -V TEST_VIEWCONFIGURATION -v
echo 
PAUSE    

REM #TEST with DEFINED LABEL and VIEW NAME  THAT ALREADY EXIST and READ MODULES FROM FILE
sde_perl viewConfiguration.pl -L CRH1090921_R1C028 -V TEST_VIEWCONFIGURATION -X MODULES.txt -v
echo 
PAUSE    

REM #TEST with DEFINED LABEL and VIEW NAME  THAT ALREADY EXIST Don't ask just DO it (-f) for force
sde_perl viewConfiguration.pl -L CRH1090921_R1C028 -V TEST_VIEWCONFIGURATION -v -f
echo 
PAUSE    